### ISSUE TITLE
Feature Request: Filter by architecture

### ISSUE THREAD

**Issue by ianmaddox** [hoonoh/aws-spot-price#805]
This tool is utterly amazing, but I find that most of the best prices are for instance types that are an architecture I can't use. I'd love to be able to pick the Architecture value (x86_64 vs arm64, for example) and have that value as one of the columns that shows up in the --wide output.

**Comment by hoonoh** [comment]
Hi, thanks for your request. I too believe this is a missing feature and will definately look into this at my spare time, probably within a week or two.

**Comment by hoonoh** [comment]
@ianmaddox Sorry for the delay, please checkout the latest release v1.1.1 with architecture support. cheers.
